export const charaDataTypes = {
	characterName: "string",
	characterType: "number",
	hiden: "number",
	remain: "number",
	weapon: "number",
	weaponOption0: "number",
	weaponOption1: "number",
	weaponOption2: "number",
	weaponPow: "number",
	weaponPowPlus: "number",
	weaponDef: "number",
	weaponDefPlus: "number",
	weaponTec: "number",
	weaponTecPlus: "number",
	weaponOption3: "number",
	weaponOption4: "number",
	weaponOption5: "number",
	stars: "number",
	charalevel: "number",
	bonusPow: "number",
	bonusDef: "number",
	bonusTec: "number",
}
