export const defaultCharaData = {
	characterName: "",
	characterType: -1,
	hiden: 0,
	remain: -1,
	weapon: -1,
	weaponOption0: -1,
	weaponOption1: -1,
	weaponOption2: -1,
	weaponPow: 0,
	weaponPowPlus: 0,
	weaponDef: 0,
	weaponDefPlus: 0,
	weaponTec: 0,
	weaponTecPlus: 0,
	weaponOption3: -1,
	weaponOption4: -1,
	weaponOption5: -1,
	stars: 0,
	charalevel: 200,
	bonusPow: 0,
	bonusDef: 0,
	bonusTec: 0,
}
